// functions/scriba/places.js
//
// Geografia REALE del mondo di Exanthia (sintesi da luoghi_per_continente.txt):
// 3 continenti col proprio bioma, e i loro luoghi con AMBIENTE (clima, acqua,
// vegetazione), CARATTERE, governo/figure note, economia e un landmark/locanda.
// È l'ossatura su cui Lo Scriba ancora le notizie: l'agent DEVE rispettare il
// clima e la natura reale di ogni luogo (non descrivere come arido un posto
// umido o boscoso, ecc.). Può inventare solo piccoli villaggi/locande MINORI.

const CONTINENTI = [
  {
    nome: "Vathriddon",
    descrizione: "Continente centrale, il più vasto e vario. Nord di montagne innevate con fortezze nella roccia; centro di grandi fiumi, laghi e foreste miste con la capitale; ovest di coste fredde e boscose a fiordi; est e sud-est di badlands aridi color ocra verso il deserto; sud di speroni rocciosi e praterie. Acqua, legname e selvaggina abbondanti al centro; frontiera dura e secca a oriente.",
    luoghi: [
      { nome: "Tirrendale", descrizione: "AMBIENTE: capitale temperata e umida, cinta dalle acque sul delta del Fiume Tirreno e su un lago interno; porto fluviale, ponti, mulini, foreste e campi intorno; pesca abbondante. Cuore politico ed economico, crogiolo di Umani, Elfi, Orchi e Nani. Governa il saggio Duca Eothen dalla Rocca Ducale (Maniero Eothen). Landmark: il Grande Emissario (il porto), l'Osteria dei Tre Incroci, il Sepolcreto di Illote. Il fiume è sacro, detto 'il Pianto dei Giganti' Ny e Ouh." },
      { nome: "Il Sacello Antico di Tirrendale", descrizione: "AMBIENTE: santuario su altura boscosa con sorgenti, presso Tirrendale, affacciato sul fiume; bosco ombroso. Mausoleo del sapere proibito: cripta a volte basse, fiammelle azzurre, tomi incatenati con Arcanite. Custodito dai Maghi Silenti (labbra cucite, occhi bendati) e accessibile solo col Sigillo Ducale. Pieno di trappole letali." },
      { nome: "Fiume Liriath", descrizione: "AMBIENTE: grande fiume ricco di pesce, dalle nevi dei monti al sud-est; in parte scorre sottoterra tra caverne di cristalli ('le stelle di sotto' dei nani). Guadi, ponti levatoi, rive di prati e canneti; via d'acqua principale per commercio. Scoperto scavando Helmvil; si dice vi nuotino pesci ciechi argentati. Punti: il Guado delle Lanterne, le Sorgenti Profonde mai raggiunte." },
      { nome: "Hakko", descrizione: "AMBIENTE: cittadina su fiume navigabile (la lore) ai piedi del nord montano, fredda e ventosa; case di pietra e legno. Vive di mercato del pesce e tessitura: i teli di Hakko, robusti e colorati, sono famosi. Mercato il giovedì. Locande: Il Gancio d'Argento (di Ferran Ulk), L'Ancora Spezzata; Tessiture di Yela Bront; armaiolo Dox Harren." },
      { nome: "Havondé", descrizione: "AMBIENTE: cittadina costiera mite dell'est, su penisola verde affacciata al mare interno; porto, pesca, campi terrazzati. CRESCIUTA DENTRO IL TESCHIO di un drago antico grande come una collina. Non si usano monete: solo baratto e favori. Punti: la Grande Cavità Cranica (piazza), la Taverna delle Costole, l'Occhio Vuoto (orbita-belvedere)." },
      { nome: "Thelén Dhir", descrizione: "AMBIENTE: città elfica nascosta in una foresta fittissima dell'est, su un'isola tra acque scure e quiete; roccia e boschi, a dominio di terre più aride sotto. Introvabile senza invito o elfi-guida in canoa. Antichissima, mai conquistata. Punti: la Torre dell'Arcanista, la Sala del Cartografo, l'Athanor dell'Alchimista; artigiani che vendono solo a chi giudicano degno." },
      { nome: "Selva Silente", descrizione: "AMBIENTE: foresta primordiale di conifere alte, innevata e avvolta da nebbia bassa perenne; sottobosco umido, ruscelli, molta selvaggina (cervi, cinghiali). CARATTERE: un silenzio assoluto e innaturale (nessun canto, vento o fruscio); chi vi entra torna cambiato, taciturno. Forse un campo di soppressione acustica antico. I cacciatori la evitano per disagio." },
      { nome: "Blumwood", descrizione: "AMBIENTE: bosco rigoglioso di latifoglie e fioriture, clima mite, suolo fertile, ruscelli e frutti. Villaggio verticale fiabesco di elfi (sulle piattaforme) e halfling (nelle tane alle radici) in armonia. Economia di frutti, miele, pupazzi di legno intarsiato. Locande: La Radice Felice (di Molo Goodbarrel, halfling), Il Nido di Rami (di Aerien Lirveth, elfa)." },
      { nome: "Boschi Sabbiosi", descrizione: "AMBIENTE: ARIDI — boscaglia rada su terreno sabbioso, frontiera fra le foreste centrali e i badlands ocra; querce basse, dune fra gli alberi, poca acqua, cacciagione minuta. CARATTERE: luogo maledetto e opprimente, luce giallognola, ombre senza vento; viandanti persi per giorni e una presenza antica che confonde e disorienta." },
      { nome: "Clan dei Demoni Grigi", descrizione: "AMBIENTE: villaggio-accampamento orchesco su alture rocciose grigie e ventose ai margini delle terre aride, acqua scarsa. Orchi grigi temuti in battaglia ma dal villaggio ordinato e colorato (giardini, mercatini di spezie). Massima: 'La belva combatte, il saggio costruisce'. Commerciano cuoio e ceramiche con Tirrendale. Locanda: La Pentola Fumante (di Nurka)." },
      { nome: "Clan dei Senza Onore", descrizione: "AMBIENTE: accampamento di tende ai margini selvaggi, fra boscaglia e badlands poveri. Orchi rossi mercenari, marchiati 'senza onore' per una fuga ancestrale; vendono le lame a chiunque ma onorano sempre il contratto. Pali con teste dei cacciatori di taglie; al centro arde da secoli il Fuoco dell'Infamia." },
      { nome: "Antica Città di Toua", descrizione: "AMBIENTE: rovine elfiche maestose su una scogliera ventosa affacciata su mare grigio, riconquistate dalla foresta; cisterne e sorgenti fra gli alberi. Fondata 3000 anni fa dai Touvari (astronomi arcani), distrutta dal Grande Silenzio (collasso delle linee ley). Catacombe con archivi sigillati; chi scende troppo torna con la mente spezzata." },
      { nome: "Helmvil", descrizione: "AMBIENTE: città nanica nelle Montagne Sussurranti (il vento tra le fenditure mormora come voci), dentro un camino vulcanico spento; Grandi Volte acustiche, Cascata d'Argento, quarzo che brilla d'azzurro. Vicino al Liriath. Fu necropoli sigillata 200 anni dopo che dall'ossidiana del Settimo Livello uscì un'ombra pietrificante; riconquistata da Borin Martelloscuro. Lampi azzurri di un Drago Blu sulle vette." },
      { nome: "Villaggio di Calen", descrizione: "AMBIENTE: porto-rifugio costiero su palafitte fra le Paludi Salmastre (mangrovie grigie, sabbie mobili, maree rapide), ovest. Ex covo di pirati e contrabbando ('Mercato delle Ombre'), oggi città fantasma avvolta da una nebbia densa e quasi senziente; si dice vi vaghino ombre di marinai a guardia di un tesoro. Le navi di Tirrendale vi si incagliano." },
      { nome: "Tassio", descrizione: "AMBIENTE: borgo tranquillo tra colline boscose e corsi d'acqua, su strada secondaria; clima mite, case di pietra e paglia. Agricoltori e allevatori silenziosi e diffidenti ma ospitali. Locanda La Meridiana (di Pera Voss), bottega di Odric Senn, fabbro Bram Colter." },
      { nome: "Ganno", descrizione: "AMBIENTE: borgo dell'entroterra su via di transito, fra campi e boschi radi, costruito sulle rovine di una torre crollata. Vivace e chiassoso grazie alla sua locanda. Governa il borgomastro Victi Rojas (gran bevitore ma con acume politico). Locande/negozi: La Locanda della Quercia (di Marta Conti, mecca dei bardi), Il Magazzino di Uldo, Bottega delle Erbe di Siria Vail." },
      { nome: "Inss", descrizione: "AMBIENTE: piccolo insediamento isolato e aspro, avamposto fra le terre selvagge. CARATTERE: straordinariamente multirazziale (umani, goblin, mezzelfi, nani, lucertoloidi) in armonia; consiglio di anziani con un rappresentante per razza; cucina e mercato fusion. Locanda Le Tre Bandiere (di Torda, goblin), Bottega di Harren Boldo, farmacia di Sshet, armeria di Dorvak." },
    ],
  },
  {
    nome: "Ehkia",
    descrizione: "Continente glaciale del nord-ovest: tundra bianca, ghiacciai, coste gelate, foreste di conifere e tigli innevati. Clima rigido tutto l'anno. Vita dura: caccia da pelliccia, pesca nelle acque gelide, insediamenti fortificati contro freddo e guerra.",
    luoghi: [
      { nome: "Nerocastello", descrizione: "AMBIENTE: cupa fortezza in rovina di pietra scura su pianura innevata presso la costa gelata; glaciale, terra di battaglie. Dominata dal goliath del fuoco Himkos: vige la legge della forza. Landmark: L'Arena di Sangue e Cenere (combattimenti all'ultimo sangue, scommesse). La Fucina di Brace, la Locanda delle Ossa, un arcanista d'identità incerta." },
      { nome: "Yotta", descrizione: "AMBIENTE: cittadina gnomica dai tetti rossi su piana nevosa presso il mare, su un grande fiume gelato; fredda ma vivace, ricca di meccanismi a vento e mulini idraulici. Porto crocevia di commercio fra continenti (un tempo sacrifici a Syrael, oggi simbolici). Quartieri: la Cittadella dei Meccanismi, il Ponte del Respiro, il Tempio di Syrael con la campana eolica, le Case del Fiume su palafitte." },
      { nome: "Nolborg", descrizione: "AMBIENTE: borgo-fortezza gelido su una lingua di terra fra due fiumi ghiacciati, costa innevata; case basse di legno scuro e pietra. Avamposto di sosta per ranger e mercanti verso le montagne o la Foresta del Tiglio Bianco. Il Grande Ponte di Pietra (a sud-ovest, con rune a Drokhan) è l'unica via stabile col resto di Ehkia." },
      { nome: "Altocolle", descrizione: "AMBIENTE: ex abitato halfling d'altura nell'interno innevato, oggi guscio carbonizzato dalla furia di un drago. Le rovine bruciano ancora di un fuoco magico violaceo alimentato dal mana residuo: un calore che non scalda ma consuma lentamente la realtà. Luogo spettrale, evitato." },
      { nome: "Foresta del Tiglio Bianco", descrizione: "AMBIENTE: foresta di tigli dalle chiome bianche di neve, rada e luminosa, suolo gelato, ruscelli ghiacciati; aria balsamica e magica. Santuario col leggendario Tiglio Bianco, le cui radici sarebbero vene di mana del mondo. Custodita da due clan druidici: le Radici Silenti (isolazioniste, magia di Drokhan) e i Gufi Bianchi (mediatori, devoti a Zenara). Cicatrici della 'Caduta delle Stelle'." },
    ],
  },
  {
    nome: "Ohzkie",
    descrizione: "Continente caldo e contrastato dell'est: a nord colline verdi, campi terrazzati, vigneti, una foresta chiara e porti sul mare; a sud una distesa sabbiosa quasi desertica; in mare isolotti rocciosi. Vita di agricoltura, viticoltura, marineria e ascesi monastica nelle sabbie.",
    luoghi: [
      { nome: "Gossvill", descrizione: "AMBIENTE: villaggio costiero mite e tranquillo sulla costa nord-ovest, terra battuta e porto; pesca, commercio, cantieri. CARATTERE: niente eroi né gloria, solo gente comune che sa vivere bene; sempre rimasto indenne da guerre, forse per la benedizione di Ny. Punti: la taverna Il Boccale Ammuffito, la Casa di Ny, la fucina del Vecchio Marn." },
      { nome: "Hopecliff", descrizione: "AMBIENTE: paesino arroccato su scogliere sul mare grigio, vento e salsedine, terrazze coltivate; pesca e caccia sono legge. CARATTERE: vivace, disordinato, multirazziale, senza nobiltà: comanda chi sa fare meglio. Punti: la Locanda del Cigno Infrastagliato, il Mercatino di Pesce e Carne all'alba, un piccolo armaiolo." },
      { nome: "Monastero dei Monaci delle Sabbie", descrizione: "AMBIENTE: monastero-torre d'ossidiana isolato tra le dune aride del sud, caldo secco, pochissima acqua; oasi e carovane. Ordine ascetico votato al silenzio e alla trascrizione dei segreti magici; ogni monaco è una 'memoria vivente'. Dieta di licheni nutriti dal mana. Custodiscono verità troppo pericolose per essere dette." },
      { nome: "Castello Dorato", descrizione: "AMBIENTE: fortezza dorata su un'isola verdeggiante in mare aperto fra nebbie e correnti gelide del Mare Argenteo; mite ma isolata, mai espugnata. Le mura brillano per la Benedizione del drago d'oro Aurexion (della Montagna Alata di Auramyr). Signore: il Conte Vaelor D'Auryn (stirpe gnomico-elfica), temuto e giusto. Vicina: la spezzata Torre del Richiamo dell'Ordine di Aetherion." },
      { nome: "Torre dell'Arcano", descrizione: "AMBIENTE: monolite di pietra scura su isolotti rocciosi battuti dal mare, cima tra nubi di elettricità statica; isolato e quasi inaccessibile. La più severa scuola di magia: silenzio assoluto, studenti senza legami, l'Esame finale conferisce il titolo di 'Arcanus'. Servita dai Monaci delle Sabbie (devoti a Myrhal). Si mormora di un demone della Caduta delle Stelle imprigionato nelle profondità." },
    ],
  },
];

module.exports = { CONTINENTI };
